### ISSUE TITLE
robomimic train.py error

### ISSUE THREAD

**Issue by Dhanushvarma** [NVlabs/mimicgen_environments#6]
The robomimic train.py script when ran with any config file other than bc.json results in error

The exact command I am running 

`python train.py --config robomimic/exps/templates/iris.json --dataset mimicgen_environments/datasets/core/stack_three_d0.hdf5`

Error : 
```
============= Model Summary =============
ObservationKeyToModalityDict: value not found, adding value to mapping with assumed low_dim modality!
ObservationKeyToModalityDict: mean not found, adding mean to mapping with assumed low_dim modality!
ObservationKeyToModalityDict: logvar not found, adding logvar to mapping with assumed low_dim modality!
```

**Comment by amandlek** [comment]
I don't see any error in that stack trace - that output is expected. Was there any other error when running this?

**Comment by amandlek** [comment]
This is because we did not include "next_obs" in order to save space for these datasets - see [this link](https://robomimic.github.io/docs/datasets/robosuite.html#extracting-observations-from-mujoco-states) for more information on extracting observations, including the "next_obs" key (which is generally only needed for offline RL methods like IRIS). You can run this on the datasets yourself to fix this issue.
